spring:
  application:
    name: hcl-bi
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .html
  # 数据库配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/bi
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 32124
    timeout: 5000
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: localhost
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.springbootinit.controller
yuapi:
  client:
    access-key: z7xmi5odgqjixg71ygwv5r2h1z8rihmc
    secret-key: ij3lh3172ok83c95cq6znonpq8ovvr52
